name: Build Godot Project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: GraveyardShift
  
jobs:
  export_web:
    name: HTML5 Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.5.1
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          pwd
          mkdir -v -p build/html5 releases final-bundle ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: godot -v --export "HTML5" ./build/html5/index.html
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/html5
          itchUsername: badcop
          itchGameId: graveyard-shift
          buildChannel: release
          
  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac" ./build/mac/$EXPORT_NAME.zip
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/mac
          itchUsername: badcop
          itchGameId: graveyard-shift
          buildChannel: macos

  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export "Windows" ../build/windows/$EXPORT_NAME.exe
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/windows
          itchUsername: badcop
          itchGameId: graveyard-shift
          buildChannel: windows
          
